export const LOG_IN_LOADING="LOG_IN_LOADING"
export const LOG_IN_SUCCESS="LOG_IN_SUCCESS"
export const LOG_IN_FAIL="LOG_IN_FAIL"

export const ADMIN_LOG_IN_LOADING="LOG_IN_LOADING"
export const ADMIN_LOG_IN_SUCCESS="LOG_IN_SUCCESS"
export const ADMIN_LOG_IN_FAIL="LOG_IN_FAIL"

export const SIGN_UP_REQUEST="SIGN_UP_REQUEST"
export const SIGN_UP_SUCCESS="SIGN_UP_SUCCESS"
export const SIGN_UP_FAILED="SIGN_UP_FAILED"

export const IS_LOGGED_IN_SUCCESS = "IS_LOGGED_IN"
export const IS_LOGGED_IN_FAIL = "IS_LOGGED_IN_FAIL"
export const LOG_OUT = "LOG_OUT"